apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx-cluster-2
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/nginx/overlays/cluster-2
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system